import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-2 p-2 sm:m-5 sm:p-5 bg-neutral-200">

        <div className="shadow bg-white rounded-t rounded-b p-5" >
          <h2 className="text-xl mb-3 font-bold">Homepage</h2>
          <nav className="flex flex-row gap-3">
            <Link className="font-bol px-2 bg-neutral-700 text-white py-1 rounded hover:bg-neutral-900" href="/">Home</Link>
            <Link className="font-bol px-2 bg-neutral-700 text-white py-1 rounded hover:bg-neutral-900" href="/property">Property</Link>
            <Link className="font-bol px-2 bg-neutral-700 text-white py-1 rounded hover:bg-neutral-900" href="/graphs">Graphs</Link>
          </nav>
        </div>
        {children}
        
      </body>
    </html>
  );
}
